definitions:
  request.OtpReq:
    properties:
      phone:
        type: string
    type: object
  request.UserDetails:
    properties:
      dob:
        type: string
      email:
        type: string
      fullname:
        type: string
      gender:
        type: string
      location:
        type: string
    required:
    - dob
    - email
    - fullname
    - gender
    - location
    type: object
  request.VerifyOtpReq:
    properties:
      otp:
        minLength: 6
        type: string
      phone:
        type: string
    required:
    - otp
    - phone
    type: object
  responce.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8081/user
info:
  contact: {}
  description: Fully fuctional dating app API
  title: Love Bites API
  version: "1.0"
paths:
  /details:
    post:
      description: Api for send user basic detials
      operationId: UserDetails
      parameters:
      - description: User details
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UserDetails'
      produces:
      - application/json
      responses:
        "201":
          description: User detials added succesfully
          schema:
            $ref: '#/definitions/responce.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/responce.Response'
      security:
      - BearerTokenAuth: []
      summary: Api for send user details
      tags:
      - AuthSvc
  /sendotp:
    post:
      description: Api for send otp to user phone
      operationId: SendOtp
      parameters:
      - description: Phone number
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.OtpReq'
      produces:
      - application/json
      responses:
        "200":
          description: Otp send succesfully
          schema:
            $ref: '#/definitions/responce.Response'
        "400":
          description: Failed to send otp
          schema:
            $ref: '#/definitions/responce.Response'
      summary: Api for send otp
      tags:
      - AuthSvc
  /upload/photos:
    post:
      consumes:
      - multipart/form-data
      description: Upload photos with additional fields using a multipart form
      operationId: upload-photos
      parameters:
      - description: Multiple photos to upload
        in: formData
        name: photos
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Photos uploaded successfully
          schema:
            $ref: '#/definitions/responce.Response'
        "400":
          description: Invalid request or contains other files
          schema:
            $ref: '#/definitions/responce.Response'
        "401":
          description: Unauthorized - User id not found
          schema:
            $ref: '#/definitions/responce.Response'
      security:
      - BearerTokenAuth: []
      summary: Upload photos with additional fields
  /verifyotp:
    post:
      description: Api for verify otp and authentication it will return token and
        user found or not
      operationId: VerifyOtpAndAuth
      parameters:
      - description: OTP and Phone number
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.VerifyOtpReq'
      produces:
      - application/json
      responses:
        "200":
          description: Verifeid succesfully
          schema:
            $ref: '#/definitions/responce.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/responce.Response'
      summary: Api for verify otp and auth
      tags:
      - AuthSvc
securityDefinitions:
  BearerTokenAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
